apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: infra
  labels:
    app: mongodb
spec:
  ports:
    - port: 27017
  selector:
    app: mongodb
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: infra
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - image: mongo:8.0.15-noble
          imagePullPolicy: IfNotPresent
          name: mongodb
          resources: 
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 1Gi
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "root"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "password"
          ports:
            - containerPort: 27017
              name: mongodb
          volumeMounts:
            - name: mongodb-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongodb-persistent-storage
          hostPath:
            path: /var/lib/k3s-storage/mongodb
            type: DirectoryOrCreate