---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: infra
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: phpmyadmin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin:latest
          imagePullPolicy: IfNotPresent
          resources: 
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: "mysql"
            - name: PMA_PORT
              value: "3306"
            - name: UPLOAD_LIMIT
              value: "200M"
            - name: MAX_EXECUTION_TIME
              value: "300"
            - name: PMA_ARBITRARY
              value: "1"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: phpmyadmin-ingress
  namespace: infra
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`admin.mysql.kube`)
    kind: Rule
    services:
    - name: phpmyadmin
      port: 80
      serversTransport: infra-default-transport@kubernetescrd
    middlewares:
    - name: infra-replace-path-middleware@kubernetescrd
    - name: infra-200mb-body-middleware@kubernetescrd