apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: infra
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: pgadmin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      securityContext:
        fsGroup: 0 
      initContainers:
        - name: fix-volume-permissions
          image: busybox 
          command: ["sh", "-c", "chmod -R g+rwX /var/lib/pgadmin"]
          volumeMounts:
          - name: pgadmin-storage
            mountPath: /var/lib/pgadmin
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:latest
          imagePullPolicy: IfNotPresent
          resources: 
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          ports:
            - containerPort: 80
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: "root@localhost.com"
            - name: PGADMIN_DEFAULT_PASSWORD
              value: "password"
          volumeMounts:
            - name: pgadmin-storage
              mountPath: /var/lib/pgadmin
      volumes:
        - name: pgadmin-storage
          hostPath:
            path: /var/lib/k3s-storage/pgadmin
            type: DirectoryOrCreate
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgadmin-ingress
  namespace: infra
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: admin.postgres.kube
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: pgadmin
              port:
                number: 80