---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-server-cert
  namespace: infra
spec:
  secretName: postgres-tls-secret
  issuerRef:
    name: selfsigned-cluster-ca
    kind: ClusterIssuer
  commonName: postgres.infra.svc.cluster.local
  dnsNames:
    - postgres
    - postgres.infra.svc.cluster.local
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-ssl-config
  namespace: infra
data:
  postgresql.conf: |
    listen_addresses='*'
    ssl = on 
    ssl_cert_file = '/etc/ssl/postgres-server/tls.crt'
    ssl_key_file = '/etc/ssl/postgres-server/tls.key'
    ssl_ca_file = '/etc/ssl/postgres-ca/ca.crt'
  pg_hba.conf: |
    hostssl all       all     0.0.0.0/0    scram-sha-256
    host    all       all     0.0.0.0/0    trust 
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: infra
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: infra
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      initContainers:
        - image: registry.k3s.kube/postgres17.6-vector:kube
          imagePullPolicy: IfNotPresent
          name: fix-ownerships
          command:
            - sh
            - -c
            - |
              chmod -R 750 /var/lib/postgresql/data && chown -R 999:999 /var/lib/postgresql/data
          volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgresql/data
          securityContext:
            runAsUser: 0
            runAsGroup: 0
      containers:
        - image: registry.k3s.kube/postgres17.6-vector:kube
          imagePullPolicy: IfNotPresent
          name: postgres
          resources: 
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 1Gi
          env:
            - name: POSTGRES_DB
              value: postgresdb
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              value: password
            - name: PGSSLMODE
              value: require
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgresql/data
            - name: postgres-ssl-config
              mountPath: /tmp/pg-config
            - name: postgres-tls
              mountPath: /etc/ssl/postgres-server
              readOnly: true
            - name: ca-secret
              mountPath: /etc/ssl/postgres-ca
              readOnly: true
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - | 
                    until [ -f /var/lib/postgresql/data/postmaster.pid ]; 
                      do echo "Waiting for active server lock..."; 
                      sleep 1; 
                    done;
                    
                    echo "Overwriting default configuration files...";

                    cp /tmp/pg-config/postgresql.conf /var/lib/postgresql/data/postgresql.conf;
                    cp /tmp/pg-config/pg_hba.conf /var/lib/postgresql/data/pg_hba.conf;

                    pg_ctl reload -D /var/lib/postgresql/data;
      volumes:
        - name: postgres-persistent-storage
          hostPath:
            path: /var/lib/k3s-storage/postgres
            type: DirectoryOrCreate
        - name: postgres-ssl-config
          configMap:
            name: postgres-ssl-config
        - name: postgres-tls
          secret:
            secretName: postgres-tls-secret
            defaultMode: 0400 
        - name: ca-secret
          secret:
            secretName: ca-secret
            items:
              - key: tls.crt 
                path: ca.crt 