---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-root-ca
  namespace: cert-manager
spec:
  isCA: true
  duration: 87600h
  secretName: postgres-ca-secret
  issuerRef:
    name: selfsigned-cluster-ca
    kind: ClusterIssuer
  commonName: Internal K8s Root CA for PostgreSQL
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: internal-ca-cluster-signer
spec:
  ca:
    secretName: postgres-ca-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-server-cert
  namespace: infra
spec:
  secretName: postgres-tls-secret
  issuerRef:
    name: internal-ca-cluster-signer
    kind: ClusterIssuer
  commonName: postgres.infra.svc.cluster.local
  dnsNames:
    - postgres
    - postgres.infra.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: infra
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: infra
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: registry.k3s.kube/postgres17.6-vector:kube
          imagePullPolicy: IfNotPresent
          name: postgres
          resources: 
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 512Mi
          env:
            - name: POSTGRES_DB
              value: postgresdb
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              value: password
            - name: PGSSLMODE
              value: require
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-persistent-storage
            - name: postgres-tls
              mountPath: /etc/ssl/postgres-server
              readOnly: true
            - name: postgres-ca
              mountPath: /etc/ssl/postgres-ca
              readOnly: true
      volumes:
        - name: postgres-persistent-storage
          hostPath:
            path: /var/lib/k3s-storage/postgres
            type: DirectoryOrCreate
        - name: postgres-tls
          secret:
            secretName: postgres-tls-secret
            defaultMode: 0400 
        - name: postgres-ca
          secret:
            secretName: postgres-ca-secret
            items:
              - key: tls.crt 
                path: ca.crt 