apiVersion: v1
kind: Service
metadata:
  name: redis-commander
  namespace: infra
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8081
  selector:
    app: redis-commander
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-commander
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-commander
  template:
    metadata:
      labels:
        app: redis-commander
    spec:
      containers:
        - name: redis-commander
          image: ghcr.io/joeferner/redis-commander
          ports:
            - containerPort: 8081
          env:
            - name: REDIS_HOSTS
              value: minikube:redis:6379:0:password
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redis-commander-ingress
  namespace: infra
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: rc.kube
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: redis-commander
              port:
                number: 80 